name = "Apocalypse Industries"
author = "TheFafalStudios"
version = "v1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df512239fcf489a7dd0f9f4fd18df54d8d2353e789cdf15c1e2d74b07e6588c6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
