name = "Apocalypse Industries"
author = "TheFafalStudios"
version = "v1.1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe3c41fdd855db7594c773b6a737d7fa7d99443bc12d0c57097aacaa0f1acfbd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
