name = "Apocalypse Industries"
author = "TheFafalStudios"
version = "v1.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5e3bef8ef8d818e6715fe0be5324c95842e5601a8e68ab952e9db6e162d4fb9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
