modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="apocalypse_gunsmithing"
version="1.1.0"
displayName="Apocalypse Gunsmithing Enchantments"
authors="Apocalypse Industries compatibility addon"
description='''Adds gun enchanting to Create: Gunsmithing: Quick Hands, Trigger Finger, Lightweight and Sharpshooter, with Create: Enchantment Industry over-level support.'''

[[mixins]]
config="apocalypse_gunsmithing.mixins.json"

[[dependencies."apocalypse_gunsmithing"]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies."apocalypse_gunsmithing"]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies."apocalypse_gunsmithing"]]
modId="ntgl"
type="required"
versionRange="[3.1.8,3.2.0)"
ordering="AFTER"
side="BOTH"

[[dependencies."apocalypse_gunsmithing"]]
modId="cgs"
type="required"
versionRange="[1.4.9,1.5.0)"
ordering="AFTER"
side="BOTH"

[[dependencies."apocalypse_gunsmithing"]]
modId="create_enchantment_industry"
type="optional"
versionRange="[2.4.0,)"
ordering="AFTER"
side="BOTH"
