"""Apply Apocalypse Atmosphere to a locally generated Euphoria 1.9.3 pack.

Python 3.10+, standard library only. Upstream shader sources are not bundled.
"""
import argparse
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import zipfile


def sha(data):
    return hashlib.sha256(data).hexdigest()


def normalized(data):
    return data.decode('utf-8').replace('\r\n', '\n').replace('\r', '')


def safe_name(name):
    path = PurePosixPath(name)
    if path.is_absolute() or '..' in path.parts or '\\' in name or ':' in name:
        raise ValueError('Unsafe archive member: ' + name)
    return name


def load_input(source):
    if source.is_file():
        with zipfile.ZipFile(source) as archive:
            if archive.testzip() is not None:
                raise ValueError('Input ZIP failed its integrity check')
            result = {}
            for entry in archive.infolist():
                if entry.is_dir():
                    continue
                safe_name(entry.filename)
                if entry.filename in result:
                    raise ValueError('Duplicate archive member: ' + entry.filename)
                result[entry.filename] = archive.read(entry)
            return result
    if not source.is_dir():
        raise ValueError('Input must be a generated shader ZIP or directory')
    result = {}
    pending = [source]
    while pending:
        directory = pending.pop()
        for child in directory.iterdir():
            # Reject symbolic links and Windows junctions before traversing them.
            if child.is_symlink() or getattr(child.lstat(), 'st_file_attributes', 0) & 0x400:
                raise ValueError('Linked shader input is unsupported: ' + str(child))
            if child.is_dir():
                pending.append(child)
            elif child.is_file():
                result[safe_name(child.relative_to(source).as_posix())] = child.read_bytes()
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--input', required=True, type=Path,
                        help='Unmodified Complementary + Euphoria 1.9.3 generated by its official patcher')
    parser.add_argument('--output-dir', required=True, type=Path,
                        help='Destination shaderpacks directory or separate test directory')
    args = parser.parse_args()
    bundle = Path(__file__).resolve().parent
    patch = json.loads((bundle / 'patch.json').read_text(encoding='utf-8'))
    files = load_input(args.input.resolve())
    # The official patcher generates both styles; this customization targets Unbound.
    common = 'shaders/lib/common.glsl'
    text = normalized(files[common])
    text, count = re.subn(r'#define SHADER_STYLE [14]\b', '#define SHADER_STYLE 4', text)
    if count != 1:
        raise ValueError('Unable to identify the Complementary shader style')
    files[common] = text.encode('utf-8')
    for name, expected in patch['licenses'].items():
        if sha(normalized(files[name]).encode('utf-8')) != expected:
            raise ValueError('Unexpected upstream license version: ' + name)
    changed = []
    for entry in patch['files']:
        name = safe_name(entry['path'])
        text = normalized(files[name])
        if sha(text.encode('utf-8')) != entry['before_sha256']:
            raise ValueError('Input differs from the required unmodified base: ' + name)
        lines = text.splitlines(True)
        for operation in reversed(entry['operations']):
            lines[operation['start']:operation['end']] = operation['replacement']
        output = ''.join(lines).encode('utf-8')
        if sha(output) != entry['after_sha256']:
            raise ValueError('Patched source hash mismatch: ' + name)
        files[name] = output
        changed.append(name)
    files['APOCALYPSE_ATMOSPHERE.txt'] = (
        'Apocalypse Atmosphere v1.1\n'
        'Based on Complementary Unbound r5.8.1 by EminGT: https://www.complementary.dev/\n'
        'Includes Euphoria Patches 1.9.3 by SpacEagle17: https://www.euphoriapatches.com/\n'
        'Generated locally through a patching mechanism; do not redistribute the resulting ZIP.\n'
        'Static source checks passed; in-game compilation and rendering remain unverified.\n'
    ).encode('utf-8')
    args.output_dir.mkdir(parents=True, exist_ok=True)
    output = args.output_dir / patch['output']
    sidecar = output.with_name(output.name + '.txt')
    if output.exists() or sidecar.exists():
        raise ValueError('Output or its settings already exists; use a new output directory')
    with zipfile.ZipFile(output, 'x', zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for name in sorted(files):
            archive.writestr(name, files[name])
    with zipfile.ZipFile(output) as archive:
        if archive.testzip() is not None:
            raise ValueError('Output ZIP failed its integrity check')
    sidecar.write_bytes((bundle / 'shader-settings.txt').read_bytes())
    print('Created:', output.resolve())
    print('SHA256:', sha(output.read_bytes()))
    print('Patched files:', len(changed))
    print('Settings:', sidecar.resolve())
    print('In-game shader selection and activation are left to the player.')


if __name__ == '__main__':
    main()
