#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 07 00:30:23 CEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.8.1_OPPRESSIVE_SUN.zip
